name: Build caddy image

on:
  push:
    branches:
      - main
    paths:
       - caddy/**
       - .github/workflows/caddy-build.yaml

  workflow_dispatch:
    
env:
  repostitory: quay.io/caracan
  context: caddy
  image_name: caddy

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out the code
        uses: actions/checkout@v6

      - name: Get Version
        id: version_tags
        run: |
            VERSION=$(jq -r '.version' ${context}/version.json)
            TAGS=latest
            if [ "${VERSION}" ] && [ "${VERSION}" != "latest" ]; then
                TAGS+=" ${VERSION}"
            fi
            if [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
                TAGS+=" git-${BASH_REMATCH[1]}"
            fi
            echo "IMAGE_TAGS=$TAGS" >> $GITHUB_OUTPUT
            echo "CONTAINER_VERSON=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Github Packages
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.repostitory }}/${{ env.image_name }}:${{ env.CONTAINER_VERSON }}
            ${{ env.repostitory }}/${{ env.image_name }}:latest
 
      - name: Verify Image
        run: docker images